language: bash

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

services:
  - docker

script:
 - export SHELLCHECK_OPTS="-e SC2002"
 - find . -name "*.sh" -print -exec shellcheck {} \;
 - docker build -t mediaserver .

notifications:
  email: false
